version: '3.5'
services:

 idaas-db:
  image: idaas-db:${IDAAS_VERSION}
  build: ./APP/idaas-db
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake --max_connections=1024
  volumes:
    - ./okp_env/var/lib/mysql:/var/lib/mysql:rw
  environment:
   - DB_SERVER_HOST=idaas-db
   - DB_SERVER_PORT=3306
   - MYSQL_USER=dmcp
   - MYSQL_PASSWORD=Dmcp321!
   - MYSQL_ROOT_PASSWOsRD=W1wDOFRTz7ELyimB
   - MYSQL_ALLOW_EMPTY_PASSWORD=false
   - MYSQL_DATABASE=mc_center
  user: root
  networks:
   idaas_net:
    aliases:
     - idaas-db

 idaas:
  image: idaas:${IDAAS_VERSION}
  build: ./APP/idaas
  ports:
    - "8020:18020"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ./idaas_env/mc-center/:/capaa/:rw
   - ./idaas_env/data/:/data/:rw
  depends_on:
   - idaas-db
  restart: always
  user: root
  networks:
   idaas_net:
    ipv4_address: 172.15.236.3
    aliases:
     - omc-idaas


networks:
  idaas_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
     driver: default
     config:
     - subnet: 172.15.236.0/24
       gateway: 172.15.236.1
