version: '2.2'
x-logging:
 &default-logging
 driver: json-file
 options:
  max-size: 100m
  max-file: "2"

services:

 idaas-db:
  image: idaas-db:${IDAAS_VERSION}
  build: ./APP/idaas-db
  ports:
    - "13306:3306"
  restart: always
  command: mysqld --character-set-server=utf8 --collation-server=utf8_bin --skip-character-set-client-handshake --max_connections=1024
  volumes:
    - ./idaas_env/var/lib/mysql:/var/lib/mysql:rw
    - ./idaas_env/etc/mysql/my-master1.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
  environment:
   - DB_SERVER_HOST=idaas-db
   - DB_SERVER_PORT=3306
   - MYSQL_USER=dmcp
   - MYSQL_PASSWORD=Dmcp321!
   - MYSQL_ROOT_PASSWORD=W1wDOFRTz7ELyimB
   - MYSQL_ALLOW_EMPTY_PASSWORD=false
   - MYSQL_DATABASE=mc_center
   - TZ=Asia/Shanghai
  user: root
  env_file:
   - .env_file
  logging: *default-logging
  networks:
   idaas_net:
    aliases:
     - idaas-db

 idaas:
  image: idaas:${IDAAS_VERSION}
  build: ./APP/idaas
  volumes:
    - ./idaas_env/data/mc-center/conf/appIndexUrlOrder.txt:/data/mc-center/conf/appIndexUrlOrder.txt:ro
  ports:
    - "18020:18020"
  depends_on:
   - idaas-db
  restart: always
  user: root
  environment:
   - TZ=Asia/Shanghai
  env_file:
   - .env_file
  logging: *default-logging
  networks:
   idaas_net:
    ipv4_address: 172.15.236.3
    aliases:
     - omc-idaas

networks:
  idaas_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.15.236.0/24
