server:
  # 请勿随意修改端口值，升级时确保端口值和初始安装时保持一致，建议端口值在第一次安装时确定好，并在后续操作中不要修改端口，否则将会导致兼容性问题
  # 可能出现的问题：
  # 1.已下载安全客户端无法使用，重新下载安装即可
  # 2.统一身份首页无法进入，在application.yml配置正确的访问路径
  address: 0.0.0.0
  port: 18020
  ssl:
    enabled: true
    key-store: classpath:javaboy.p12
    key-alias: tomcathttps
    key-store-password: 111111
    #key-store-type: PKCS12
    enabled-protocols: TLSv1.2
    ciphers: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_DSS_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_SHA256,TLS_ECDHE_RSA_WITH_AES_128_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_SHA,TLS_ECDHE_RSA_WITH_AES_256_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_SHA384,TLS_ECDHE_RSA_WITH_AES_256_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_SHA,TLS_DHE_RSA_WITH_AES_128_SHA256,TLS_DHE_RSA_WITH_AES_128_SHA,TLS_DHE_DSS_WITH_AES_128_SHA256,TLS_DHE_RSA_WITH_AES_256_SHA256,TLS_DHE_DSS_WITH_AES_256_SHA,TLS_DHE_RSA_WITH_AES_256_SHA


spring:
  # MySQL数据源配置
  datasource:
    # IPv4 连接地址
    url: jdbc:mysql://idaas-db:3306/mc_center
    # IPv6 连接地址
    #url: jdbc:mysql://[::1]:3306/mc_center
    username: dmcp
    password: Dmcp321!
  # MQ配置信息
  #kafka:
    #properties:
      #username: alice
      #password: hzmc456
    #bootstrap-servers: 127.0.0.1:9092
  # RedisCluster
  redis:
    enabled: false
    cluster:
      nodes: 127.0.0.1:18379,127.0.0.1:18379,127.0.0.1:18379
      password:

# 是否开启租户模式
tenant.enableTenant: false

# 项目访问路径配置
uc-center:
  accessPath: https://127.0.0.1:18020
  # 是否开启对外接口日志
  interfaceLogSwitch: false

appTempToken: cdd171a6-779d-445c-a757-5bbc0e712e62

builtinApp: data-notice,data-drcc

# swagger开关
swagger.enable: false

#主机的真实ip地址  kafka心跳开关控制
heartbeat:
  enable: false
  instanceIp: 127.0.0.1

# 安全客户端模块地址
#secure_client_address: 127.0.0.1:8081

#身份模块开关
identity.enable: true
