#!/bin/bash
if [ -f /onekeeper/idaas-docker/docker-compose.yaml ];then
cd /onekeeper/idaas-docker
sudo docker-compose -f /onekeeper/idaas-docker/docker-compose.yaml  stop
#sudo systemctl stop osm
#sudo systemctl disable osm
fi
