#!/bin/bash
if [ -f /onekeeper/idaas-docker/docker-compose.yaml ];then
cd /onekeeper/idaas-docker
sudo docker-compose -f /onekeeper/idaas-docker/docker-compose.yaml up -d
sleep 5s
sudo docker ps -a --format "table {{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}\t{{.Names}}" |grep idaas
fi